use crate::*;

pub(crate) fn read_validation_statuses(
    features: &[Feature],
) -> Result<BTreeMap<String, ValidationStatus>, Box<dyn Error>> {
    let mut statuses = BTreeMap::new();
    for corpus in VALIDATION_CORPORA {
        let path = validation_status_path(corpus.id);
        if path.exists() {
            let status = read_corpus_status(&path)?;
            if status.corpus_id != corpus.id {
                return Err(boxed_error(format!(
                    "{} declares corpus_id `{}`, expected `{}`",
                    path.display(),
                    status.corpus_id,
                    corpus.id
                )));
            }
            for (feature_id, feature_status) in status.features {
                if !features.iter().any(|feature| feature.id == feature_id) {
                    return Err(boxed_error(format!(
                        "{} records unknown feature `{feature_id}`",
                        path.display()
                    )));
                }
                statuses
                    .entry(feature_id.clone())
                    .or_insert_with(|| ValidationStatus::new(&feature_id))
                    .corpora
                    .insert(corpus.id.to_owned(), feature_status);
            }
        }
    }
    Ok(statuses)
}

pub(crate) fn validation_status_path(corpus: &str) -> PathBuf {
    validation_status_path_from(Path::new("."), corpus)
}

pub(crate) fn validation_status_path_from(root: &Path, corpus: &str) -> PathBuf {
    root.join("validation")
        .join("corpora")
        .join(corpus)
        .join("status.toml")
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct CorpusStatusFile {
    pub(crate) corpus_id: String,
    #[serde(default)]
    pub(crate) features: BTreeMap<String, CorpusStatus>,
}

pub(crate) fn read_corpus_status(path: &Path) -> Result<CorpusStatusFile, Box<dyn Error>> {
    let text = fs::read_to_string(path)?;
    let mut status: CorpusStatusFile = toml::from_str(&text)
        .map_err(|error| boxed_error(format!("{}: {error}", path.display())))?;
    for feature in status.features.values_mut() {
        if feature.evidence_input_count == 0 && !feature.legacy_evidence_inputs.is_empty() {
            feature.evidence_input_count = feature.legacy_evidence_inputs.len();
        }
    }
    Ok(status)
}

pub(crate) fn write_validation_statuses(
    statuses: &BTreeMap<String, ValidationStatus>,
    selected_corpora: &BTreeSet<String>,
) -> Result<(), Box<dyn Error>> {
    write_validation_statuses_from(Path::new("."), statuses, selected_corpora)
}

pub(crate) fn write_validation_statuses_from(
    root: &Path,
    statuses: &BTreeMap<String, ValidationStatus>,
    selected_corpora: &BTreeSet<String>,
) -> Result<(), Box<dyn Error>> {
    for corpus in VALIDATION_CORPORA {
        if !selected_corpora.contains(corpus.id) {
            continue;
        }
        let mut corpus_status = CorpusStatusFile {
            corpus_id: corpus.id.to_owned(),
            features: BTreeMap::new(),
        };
        for (feature_id, status) in statuses {
            if !validation_manifest_path_from(root, feature_id, corpus.id).exists() {
                continue;
            }
            if let Some(feature_status) = status.corpora.get(corpus.id) {
                corpus_status
                    .features
                    .insert(feature_id.clone(), feature_status.clone());
            }
        }
        let path = validation_status_path_from(root, corpus.id);
        if corpus_status.features.is_empty() {
            if path.exists() {
                fs::remove_file(&path)?;
            }
            continue;
        }
        fs::create_dir_all(
            path.parent()
                .ok_or_else(|| boxed_error("status path has no parent"))?,
        )?;
        let text = toml::to_string_pretty(&corpus_status)?;
        write_atomic_text(
            &path,
            &format!("# Generated by `cargo xtask validate --update`. Do not hand-edit.\n{text}"),
        )?;
    }
    Ok(())
}

pub(crate) fn recorded_corpus_status_passed(corpus_status: Option<&CorpusStatus>) -> bool {
    let Some(corpus_status) = corpus_status else {
        return false;
    };
    corpus_status.passed
        && corpus_status.fixture_count > 0
        && corpus_status.compared_count == corpus_status.fixture_count
        && corpus_status.evidence_schema_version == Some(VALIDATION_EVIDENCE_SCHEMA_VERSION)
        && corpus_status
            .evidence_hash
            .as_deref()
            .is_some_and(is_sha256)
        && (corpus_status.evidence_input_count > 0
            || !corpus_status.legacy_evidence_inputs.is_empty())
}
pub(crate) fn write_atomic_text(path: &Path, text: &str) -> Result<(), Box<dyn Error>> {
    write_atomic_bytes(path, text.as_bytes())
}

pub(crate) fn write_atomic_bytes(path: &Path, bytes: &[u8]) -> Result<(), Box<dyn Error>> {
    let parent = path
        .parent()
        .ok_or_else(|| boxed_error(format!("{} has no parent", path.display())))?;
    fs::create_dir_all(parent)?;
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| boxed_error(format!("{} has no file name", path.display())))?;
    let nonce = SystemTime::now().duration_since(UNIX_EPOCH)?.as_nanos();
    let tmp = parent.join(format!(".{file_name}.{nonce}.tmp"));
    fs::write(&tmp, bytes)?;
    match fs::rename(&tmp, path) {
        Ok(()) => Ok(()),
        Err(error) if path.exists() => {
            fs::remove_file(path)?;
            fs::rename(&tmp, path).map_err(|rename_error| {
                boxed_error(format!(
                    "failed to replace {} after initial rename error {error}: {rename_error}",
                    path.display()
                ))
            })
        }
        Err(error) => Err(boxed_error(format!(
            "failed to replace {}: {error}",
            path.display()
        ))),
    }
}
