use crate::*;

pub(crate) fn read_validation_statuses(
    features: &[Feature],
) -> Result<BTreeMap<String, ValidationStatus>, Box<dyn Error>> {
    let mut statuses = BTreeMap::new();
    for corpus in VALIDATION_CORPORA {
        let path = validation_status_path(corpus.id);
        if path.exists() {
            let status = read_corpus_status(&path)?;
            if status.corpus_id != corpus.id {
                return Err(boxed_error(format!(
                    "{} declares corpus_id `{}`, expected `{}`",
                    path.display(),
                    status.corpus_id,
                    corpus.id
                )));
            }
            for (feature_id, feature_status) in status.features {
                if !features.iter().any(|feature| feature.id == feature_id) {
                    return Err(boxed_error(format!(
                        "{} records unknown feature `{feature_id}`",
                        path.display()
                    )));
                }
                statuses
                    .entry(feature_id.clone())
                    .or_insert_with(|| ValidationStatus::new(&feature_id))
                    .corpora
                    .insert(corpus.id.to_owned(), feature_status);
            }
        }
    }
    Ok(statuses)
}

pub(crate) fn validation_status_path(corpus: &str) -> PathBuf {
    Path::new("validation")
        .join("corpora")
        .join(corpus)
        .join("status.toml")
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct CorpusStatusFile {
    pub(crate) corpus_id: String,
    #[serde(default)]
    pub(crate) features: BTreeMap<String, CorpusStatus>,
}

pub(crate) fn read_corpus_status(path: &Path) -> Result<CorpusStatusFile, Box<dyn Error>> {
    let text = fs::read_to_string(path)?;
    toml::from_str(&text).map_err(|error| boxed_error(format!("{}: {error}", path.display())))
}

pub(crate) fn write_validation_statuses(
    statuses: &BTreeMap<String, ValidationStatus>,
    selected_corpora: &BTreeSet<String>,
) -> Result<(), Box<dyn Error>> {
    for corpus in VALIDATION_CORPORA {
        if !selected_corpora.contains(corpus.id) {
            continue;
        }
        let mut corpus_status = CorpusStatusFile {
            corpus_id: corpus.id.to_owned(),
            features: BTreeMap::new(),
        };
        for (feature_id, status) in statuses {
            if let Some(feature_status) = status.corpora.get(corpus.id) {
                corpus_status
                    .features
                    .insert(feature_id.clone(), feature_status.clone());
            }
        }
        if corpus_status.features.is_empty() {
            continue;
        }
        let path = validation_status_path(corpus.id);
        fs::create_dir_all(
            path.parent()
                .ok_or_else(|| boxed_error("status path has no parent"))?,
        )?;
        let text = toml::to_string_pretty(&corpus_status)?;
        write_atomic_text(
            &path,
            &format!("# Generated by `cargo xtask validate --update`. Do not hand-edit.\n{text}"),
        )?;
    }
    Ok(())
}

pub(crate) fn recorded_corpus_passed(
    feature: &Feature,
    status: Option<&ValidationStatus>,
    corpus: &str,
) -> bool {
    if !feature
        .validation_required
        .iter()
        .any(|item| item == corpus)
    {
        return false;
    }
    let Some(corpus_status) = status.and_then(|status| status.corpora.get(corpus)) else {
        return false;
    };
    corpus_status.passed
        && corpus_status.fixture_count > 0
        && corpus_status.compared_count == corpus_status.fixture_count
        && corpus_status.evidence_schema_version == Some(VALIDATION_EVIDENCE_SCHEMA_VERSION)
        && corpus_status
            .evidence_hash
            .as_deref()
            .is_some_and(is_sha256)
        && !corpus_status.evidence_inputs.is_empty()
}
#[cfg(test)]
pub(crate) fn recorded_overall_validated(
    feature: &Feature,
    status: Option<&ValidationStatus>,
) -> bool {
    feature.implemented
        && !feature.validation_required.is_empty()
        && feature
            .validation_required
            .iter()
            .all(|corpus| recorded_corpus_passed(feature, status, corpus))
}

pub(crate) fn corpus_passed_at(
    feature: &Feature,
    status: Option<&ValidationStatus>,
    corpus: &str,
    validation_root: &Path,
) -> bool {
    if !feature
        .validation_required
        .iter()
        .any(|item| item == corpus)
    {
        return false;
    }
    let Some(corpus_status) = status.and_then(|status| status.corpora.get(corpus)) else {
        return false;
    };
    if !corpus_status.passed {
        return false;
    }
    if corpus_status.fixture_count == 0
        || corpus_status.compared_count != corpus_status.fixture_count
    {
        return false;
    }
    if corpus_status.evidence_schema_version != Some(VALIDATION_EVIDENCE_SCHEMA_VERSION) {
        return false;
    }
    let Some(recorded_evidence_hash) = corpus_status.evidence_hash.as_deref() else {
        return false;
    };
    let manifest_path = validation_root
        .join("corpora")
        .join(corpus)
        .join("features")
        .join(format!("{}.toml", feature.id));
    if !manifest_path.exists()
        || hash_file(&manifest_path)
            .map(|hash| hash != corpus_status.manifest_hash)
            .unwrap_or(true)
    {
        return false;
    }
    let repo_root = validation_root.parent().unwrap_or_else(|| Path::new("."));
    read_validation_manifest(&manifest_path)
        .and_then(|manifest| build_validation_evidence(repo_root, &manifest_path, &manifest))
        .map(|evidence| {
            evidence.schema_version == VALIDATION_EVIDENCE_SCHEMA_VERSION
                && evidence.sha256 == recorded_evidence_hash
                && !evidence.inputs.is_empty()
        })
        .unwrap_or(false)
}

pub(crate) fn overall_validated(feature: &Feature, status: Option<&ValidationStatus>) -> bool {
    overall_validated_at(feature, status, Path::new("validation"))
}

pub(crate) fn overall_validated_at(
    feature: &Feature,
    status: Option<&ValidationStatus>,
    validation_root: &Path,
) -> bool {
    feature.implemented
        && !feature.validation_required.is_empty()
        && feature
            .validation_required
            .iter()
            .all(|corpus| corpus_passed_at(feature, status, corpus, validation_root))
}

pub(crate) fn sync_feature_validation_flags(
    features: &[Feature],
    statuses: &BTreeMap<String, ValidationStatus>,
) -> Result<(), Box<dyn Error>> {
    sync_feature_validation_flags_at(
        features,
        statuses,
        Path::new("features"),
        Path::new("validation"),
    )
}

pub(crate) fn sync_feature_validation_flags_at(
    features: &[Feature],
    statuses: &BTreeMap<String, ValidationStatus>,
    features_root: &Path,
    validation_root: &Path,
) -> Result<(), Box<dyn Error>> {
    for feature in features {
        let validated = overall_validated_at(feature, statuses.get(&feature.id), validation_root);
        if validated == feature.validated {
            continue;
        }
        let path = features_root.join(&feature.id).join("feature.toml");
        let text = fs::read_to_string(&path)?;
        let replacement = format!("validated = {validated}");
        let mut replaced = false;
        let rewritten = text
            .lines()
            .map(|line| {
                if line.trim_start().starts_with("validated =") {
                    replaced = true;
                    replacement.as_str()
                } else {
                    line
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
        if !replaced {
            return Err(boxed_error(format!(
                "{} is missing `validated`",
                path.display()
            )));
        }
        write_atomic_text(&path, &format!("{rewritten}\n"))?;
    }
    Ok(())
}

pub(crate) fn write_atomic_text(path: &Path, text: &str) -> Result<(), Box<dyn Error>> {
    write_atomic_bytes(path, text.as_bytes())
}

pub(crate) fn write_atomic_bytes(path: &Path, bytes: &[u8]) -> Result<(), Box<dyn Error>> {
    let parent = path
        .parent()
        .ok_or_else(|| boxed_error(format!("{} has no parent", path.display())))?;
    fs::create_dir_all(parent)?;
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| boxed_error(format!("{} has no file name", path.display())))?;
    let nonce = SystemTime::now().duration_since(UNIX_EPOCH)?.as_nanos();
    let tmp = parent.join(format!(".{file_name}.{nonce}.tmp"));
    fs::write(&tmp, bytes)?;
    match fs::rename(&tmp, path) {
        Ok(()) => Ok(()),
        Err(error) if path.exists() => {
            fs::remove_file(path)?;
            fs::rename(&tmp, path).map_err(|rename_error| {
                boxed_error(format!(
                    "failed to replace {} after initial rename error {error}: {rename_error}",
                    path.display()
                ))
            })
        }
        Err(error) => Err(boxed_error(format!(
            "failed to replace {}: {error}",
            path.display()
        ))),
    }
}
